### ISSUE TITLE
List inheritance

### ISSUE THREAD

**Issue by khornel** [tyd-format/TyD#1]
I have a lot of cases where I would rather replace the values of a list when inheriting, instead of prepending to it. For instance: I have an object that defines a bounding polygon as a list of points, prepending points in the heir would end up breaking the bounding polygon.

A possible solution could be a special sign, possibly at the beginning of a list, to denote where to put the heirs' nodes, such that omitting the special sign would replace the heirs' list completely. E.g.
```
Thing *handle Base
{
    List  [ Value1 ; Value2 ]
}

Thing2 *source Base
{
    List  [ Value3; *; Value4 ] #result is [ Value3; Value1; Value2; Value4 ]
}

Thing2 *source Base
{
    List  [ Value2 ] #result is [ Value2 ]
}
```

Possible issues would be unpredictable behavior when several heirs in a tree wants to replace the same list. I would argue that is for the application to solve, though. E.g.

```
Thing *handle Base
{
    List  [ Value1 ]
}

Thing2 *source Base *handle Base2
{
    List  [ *; Value2 ] #result is [ Value1; Value2 ]
}

Thing3 *source Base2 *handle Base3
{
    List  [ Value3 ] #result is [ Value3 ]
}

Thing4 *source Base3
{
    List  [ *; Value4 ] #We have now lost Value1 and Value2
}
```

**Comment by khornel** [comment]
I might just be dense, but on further inspection, isn't the inheritance relationship reversed in TyD?
For instance:
```
Thing *handle Base
{
	Value BaseValue
}

Thing2 *source Base
{
	Value NewValue
}
```

Thing2's Value will be replaced with "BaseValue", meaning whatever you define in an heir is never used and just redundant? Shouldn't it be the other way around?

**Comment by TynanSylvester** [comment]
You're right about the issues with list inheritance. What we did on RimWorld was just a simple "Inherit=false" XML attribute on the inheriting list. I was thinking there should be a similar attribute in the TyD spec too. I think it's better to just have a simple "noinherit" and then rewrite the whole list; having arbitrary placement of parent data is getting too complex IMO to be worth the typically small reduction in data duplication.

As for reversal of inheritance relationship, the heir's data should take precendence over the source. I'll have to check to make sure the spec actually says that.

Will address these in a spec update.

**Comment by TynanSylvester** [comment]
Ok, I reworked the spec based on this.

The noinherit attribute is specced but not in TyDSharp yet. However, it is a battle-tested design used in RimWorld for years so I think it should work. Very open to other ideas here though.

**Comment by khornel** [comment]
The arbitrary placement of source data is definitely overkill, thinking about it. The *noinherit attribute seems a bit verbose, though, it kind of breaks the neat record value structure. Couldn't it be a special character before or after the record name instead?

**Comment by TynanSylvester** [comment]
There's going to be other attributes using the star-attribute syntax. Plus
noinherit is pretty rare, so I think consistency and readability beats
absolutely compressing the number of characters to the tiniest possible.

**Comment by TynanSylvester** [comment]
Just as a reference, I just checked the RimWorld data. It's quite a large game with a lot of data, but despite all that volume, the Inherit="False" tag only appears 20 times.

**Comment by khornel** [comment]
Considering this will only apply to collections, which usually have data after a new line, my comment regarding file layout was irrelevant.

I don't use inheritance for any data internally in Software Inc., but the default behavior for mods is to not inherit list data, as in my boundary example, you would either want to replace the values or keep them intact. In cases where you would, though, having a noinherit attribute is infinitely better than having to copy paste the source data over manually.

Just spitballing here, of course, but you could call it *replace instead, and use *noinherit on source records to disallow prepending its value(s) to heirs. It could protect data and avoid misunderstandings, like accidentally appending points to a polygon, which would be an easy mistake to make.

**Comment by TynanSylvester** [comment]
*Replace is definitely a valid idea. I'll watch to see if it comes up repeatedly enough to be desired in the spec. Though in RimWorld we never needed something like that.

Anyway, I'll close it since this is slipping to other topics. Thanks very much!
