### ISSUE TITLE
XPath Patching Usage Patterns

### ISSUE THREAD

**Issue by obuw** [tyd-format/TyD#3]
Hi Tynan,

I heard you're looking for usage patterns to improve the design of patching for TyD. Since I don't have a twitter account I thought I'd post here. Hope that's okay.

I try to use patches in my personal mods as much as possible to improve compatibility, and one thing that would be kind of helpful would be kind of a batch replace operation. 

For example, to modify the Damage and AP of a bullet, I need to do two separate operations:

```
<Operation Class="PatchOperationReplace"><xpath>Defs/ThingDef[defName="Bullet_6x24mmCharged"]/projectile/damageAmountBase</xpath>
    <value><damageAmountBase>16</damageAmountBase></value>
</Operation>
<Operation Class="PatchOperationReplace"><xpath>Defs/ThingDef[defName="Bullet_6x24mmCharged"]/projectile/armorPenetrationBase</xpath>
    <value><armorPenetrationBase>0.7</armorPenetrationBase></value>
</Operation>
```

Of course if I batch it together and overwrite the projectile itself like this:
```
<Operation Class="PatchOperationReplace"><xpath>Defs/ThingDef[defName="Bullet_6x24mmCharged"]/projectile</xpath>
    <projectile>
        <value><damageAmountBase>16</damageAmountBase></value>
        <value><armorPenetrationBase>0.7</armorPenetrationBase></value>
    </projectile>
</Operation>
```
... then it would erase all the other properties of the projectile, like secondaryDamage, etc.

It would be nice if I could just bundle them together somewhat like this:
```
<Operation Class="PatchOperationReplace"><xpath>Defs/ThingDef[defName="Bullet_6x24mmCharged"]/projectile/*</xpath>
    <value><damageAmountBase>16</damageAmountBase></value>
    <value><armorPenetrationBase>0.7</armorPenetrationBase></value>
</Operation>
```
... without touching any of the other values of the object.

Another potential nitpick is that having to repeat the property 3 times in a replace operation kinda feels redundant and wordy. For example:

```
<Operation Class="PatchOperationReplace"><xpath>Defs/ThingDef[defName="Bullet_6x24mmCharged"]/projectile/damageAmountBase</xpath>
    <value><damageAmountBase>16</damageAmountBase></value>
</Operation>
```

... could perhaps be shortened to something like:

```
<Operation Class="PatchOperationReplace"><xpath>Defs/ThingDef[defName="Bullet_6x24mmCharged"]/projectile/damageAmountBase</xpath>
    <value>16</value>
</Operation>
```

I don't know if this is at all feasible, just a thought.

**Comment by TynanSylvester** [comment]
Thanks! This is definitely a pattern I'll be keeping in mind.
